### ISSUE TITLE
Elasticsearch Checker

### ISSUE THREAD

**Issue by derfeineherr** [bretrzaun/statuspage#7]
Thank you for the great Work with that useful and well programmed Library!
Could you please provide a Check for Elasticsearch that accepts an Client to ensure that the Elasticsearch Cluster is available for Searching an Indexing?

There is for Example an ping Endpoint that could be used for this.
https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/ElasticsearchPHP_Endpoints.html#Elasticsearch_Clientping_ping

For know i am using the UrlCheck to do exactly this. But there is a litte extra Work necessary to achieve the same result.

Thank you in advance,
Harry

**Comment by bretrzaun** [comment]
I added an ElasticsearchCheck - see develop Branch

**Comment by derfeineherr** [comment]
Wow, 6 Hours Solution Time!
Thank you very much. Keep up the good work!
